### ISSUE TITLE
Update manifest to use the new add-on name

### ISSUE THREAD

**Issue by mrchrisadams** [eveahe/greenbeam#11]
Right now, we have the old Firefox Lightbeam bits in the manifest.json.

The manifest.json controls what is shown in the add-on list when an extension is installed.

We'd need to update a few things here, particularly:

- [x] update name
- [x] update description
- [x] update homepage_url 
- [x] update icons 
- [x] update browser_action (default icon and title}

**Comment by eveahe** [comment]
Just updated! Thanks, Chris!
