### ISSUE TITLE
Represent how domains are powered by by coloring nodes in the graph

### ISSUE THREAD

**Issue by mrchrisadams** [eveahe/greenbeam#5]
Hi Eve!

I'm moving the issues from my repo to here, mainly so there's a record, as I'd like to remove the issues from my old repo - I think having two sets of issues is confusing.

I totally accept the what you're after may be different from them, so I won't be all butthurt if you close them. From the previous repo:

> In the force directed diagram, we want to be able to colour the nodes based on whether > they run on green power or not, by checking every domain discovered against the Green Web > API.
>
> If they use renewable power, shade 'em green.
> Implementing this
> 
> Lightbeam uses a force directed layout from D3, which is rendered onto a canvas element, > presumably for speed.
> 
> You can see the draw nodes function below:
> 
> https://github.com/mrchrisadams/greenbeam/blob/master/src/js/viz.js#L158
> 
> Right now, I think the nodes are built in here, in transformData, which gets a list of > websites from …
> 
> https://github.com/mrchrisadams/greenbeam/blob/master/src/js/lightbeam.js#L216
> 
> … this bit here in the call to init which is getting them from storechild.js:
> 
> https://github.com/mrchrisadams/greenbeam/blob/master/src/js/lightbeam.js#L8
> 
> So if we hooked into transformData, we could enrich them with data, but it might be > better doing in the background and updating the set instead.

**Comment by eveahe** [comment]
Closing this issue, thanks Chris!
